version: '3.8'

services:
  yew-ui:
    volumes:
      - type: bind
        source: ../
        target: /app
      - yew-ui-target-cache:/app/yew-ui/target
      - yew-ui-cargo-registry-cache:/usr/local/cargo/registry
    build:
      dockerfile: ../docker/Dockerfile.yew
    command: bash -c "cd app/zigit-web && trunk serve"
    # environment:
    #   - ACTIX_PORT=${ACTIX_PORT:-8080}
    #   - TRUNK_SERVE_PORT=${TRUNK_SERVE_PORT:-80}
    #   - ENABLE_OAUTH=true
    #   - LOGIN_URL=http://localhost:${ACTIX_PORT:-8080}/login
    # ports:
    #   - "${TRUNK_SERVE_PORT:-80}:${TRUNK_SERVE_PORT:-80}"
